### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ivanik7** [ivanik7/magtu-bot#4]
Тут накопилось некоторое количество идей, которые надо бы сделать, но ~~лень~~ руки не доходят. Что бы ничего не забыть напишу тут список:
- [ ] Расписание для преподавателей
- [ ] Расписание для кабинетов
- [ ] Вернуть команды с аргументами
- [x] Реагирование на пересланные сообщения
- [ ] Настройки для беседы: отключить/включить кнопки, сменить знак перед сообщениями
- [ ] Уведомление о новых заменах
- [ ] Вывод расписания сразу за три дня
- [ ] Автоматическое добавление в закрепленные сообщения беседы расписания
- [ ] Поддержка Telegram
- [ ] Ведение статистики по запросам
- [ ] Живая обложка в группе

**Comment by ivanik7** [comment]
Переместил в trello https://trello.com/b/QAD0tOiE/%D0%BC%D0%BF%D0%BA-%D0%B1%D0%BE%D1%82
